name: Deploy to Pages
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'demo/**'
jobs:
  build-and-deploy-demo:
    env:
      ENABLE_AUTO_DEPLOY: ${{ !!secrets.ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: env.ENABLE_AUTO_DEPLOY == 'true'
        uses: actions/checkout@v1
      - name: Build and Deploy Demo to GitHub Pages
        if: env.ENABLE_AUTO_DEPLOY == 'true'
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: demo/dist
          BUILD_SCRIPT: yarn && yarn run build:demo
